
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd
spec:
  project: default
  source:
    # SUSTITUYE ESTA LÍNEA CON LA URL DE TU REPOSITORIO GIT
    repoURL: https://github.com/Nettaro-Consulting/GKE-OBS.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true